---
title: \normalsize Utilization of Antiemetic Medication as a Marker of Healthcare
  Disparities in Anesthesia \newline A Bayesian Hierarchical Model Using the National
  Anesthesia Clinical Outcomes Registry
csl: Bibliography/anesthesia-and-analgesia.csl
fontfamily: pslatex
output:
  pdf_document: default
  html_document: default
  word_document:
    reference_docx: mystyles.docx
bibliography: Bibliography/AQI_bibliography31May2016.bib
---
\setlength{\parindent}{0ex}

##### Authors

Michael H. Andreae, M.D., Department of Anesthesiology, Montefiore Medical Center, Albert Einstein College of Medicine, Bronx, NY

Jonah S. Gabry, M.A., Department of Statistics, Columbia University, New York, NY

Ben Goodrich, PhD., Department of Political Science, Columbia University, New York, NY

Robert S White, M.D., Department of Anesthesiology, Weill Cornell Medical Center, New York, NY

Charles Hall, PhD, Department of Epidemiology & Population Health, Albert Einstein College of Medicine, Bronx, NY

##### Corresponding author:

Michael Andreae, MD, Address: Department of Anesthesiology, Montefiore Medical Center, 111 E 210th Street, Bronx, NY 10467, Tel: +1 (718) 920 2802, Email: mandreae@montefiore.org

##### Acknowledgement

This research is supported in part by the National Center for Advancing Translational Sciences (NCATS), a component of the National Institutes of Health (NIH), through CTSA grant numbers 5KL2TR001071-03 and UL1 TR001073. Its contents are solely the responsibility of the authors and do not necessarily represent the official views of the NIH.

##### Conflicts of Interest: None

**Number of words in Abstract (300), in Introduction (353), and in Discussion (921)**

\newpage

#Abstract

**Background:** US Health care disparities persist despite repeated countermeasures. Research identified race, ethnicity, gender, and socio-economic status as predictors, mediated through individual provider and/or systemic biases; little research exists in anesthesiology. We investigated antiemetic prophylaxis as a surrogate marker for anesthesia quality by individual providers, because antiemetics are universally available, indicated independent of patient co-morbidities and not yet impacted by regulatory or financial constraints. 

**Methods:** We hypothesize that socioeconomic markers (like insurance status or median income in the patients home zip code area) predict antiemetic prophylaxis as a marker of anesthesia quality. We fit a classical and Bayesian mixed logistic regression models in the subset of anesthesia cases in the National Anesthesia Clinical Outcomes Registry (NACOR) with complete electronic anesthesia records to test our hypothesis. 

**Results:** Seven institutions reported on antiemetic utilization for 441,645 anesthesia cases, but only 173,133 cases included details on insurance information, even fewer n=92683) contained complete data on procedure codes and providers identifiers, out of the 12 million cases in NACOR 2013. Bivariate analysis, multivariate logistic regression and our Bayesian hierarchical model all showed a strong and statistically significant association between socioeconomic markers and the odds of receiving antiemetic prophylaxis; for Medicaid versus commercially insured patients, the odds ratio of receiving the antiemetic ondansetron is 0.85 in our Bayesian hierarchical mixed regression model, with a 95% Bayesian credible interval of [0.81, 0.89] with similar inferences in classical regression models. 

**Discussion:** Our data support the notion that patients with lower socioeconomic status receive inferior anesthesia care, after we controlled for important patient characteristics and for procedure and provider influences. Our sample may not be representative and may fail to account for all confounders. Our results point to possible unappreciated healthcare disparities in anesthesia at the provider level which are worrisome and deserve further investigation and vigorous countermeasures.

```{r, global_options, echo=FALSE}
suppressWarnings(library(knitr))
# set options
opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE)
eval_everything=FALSE
```

\newpage

\setcounter{secnumdepth}{2}
\setlength{\parindent}{10ex}

# Introduction

## Background
The healthcare disparities in the United States of America described decades ago by Gornick[@Gornick_8703185], persist and are linked to social determinants of health and equality[@IOM_2003;@Cooper_22566148; @Schoen_24226092].
Poverty, poor education, differences in medical insurance coverage, geographic location, legal or social status, race & gender, patient and community attitudes & perceptions and, last but not least, provider bias lead to healthcare disparities[@Silber_23719571]. A systematic review by Haider suggested that insurance status, median income, race, ethnicity, and socioeconomic status predict trauma outcomes, independent of injury type[@Haider_23609267]. LaPar showed that Medicaid and uninsured payer status confer increased risk-adjusted mortality for major surgery in the National Inpatient Database [@LaPar2010].

## Significance
Do healthcare disparities exist also in anesthesia? A systematic review and meta-analysis by Meghani raises alarm about the persistent racial and ethnic disparities in the treatment of pain, clearly a domain of anesthesiologists[@Meghani_22239747]. We described language as barrier to access chronic pain services[@Shaparin_24747766]. Jimenez found disparities in pain treatment in children[@Jimenez_20173265]. Unfortunately, apart from labor analgesia[@Toledo_22075013; @Glance_17197841; @Rust_15343221; @Elisha_22403965] and pain medicine[@Glance2015;@Gaba_10720368;@Leape_7503827;@Silber_10861159], the literature on anesthesia related health disparities seems sparse[@Silber_23719571; @Tighe2012], while Spencer et alt worried that "differences in payment between public and private payers may result in inferior care", and more patient safety events [@Spencer2015].

## Objective

We propose to investigate antiemetic utilization as a marker of quality anesthesia care and health care disparity. Patients perceive Postoperative nausea and vomiting (PONV) is an important outcome [@Wender2009]. Previous research showed remarkable variability between providers in antiemetic utlization, possibly due to gaps in knowledge, provider perceptions of importance of PONV as an outcome for the patient at hand, leading to unterutlization of proven therapies[@MacarioChungWeinger2001]. Several characteristics make antiemetic utilization a good marker as 

1. antiemetic utilization is relatively independent of patient co-morbidities, 
2. antiemetic utilization is the sole responsibility of anesthesia providers [@MacarioChungWeinger2001],
3. antiemetic utilization is not (yet) influenced by regulatory or insurance constraints,
4. antiemetic utilization clearly improves outcomes, which matter to patients[@Wender2009; @Apfel_15190136], and
4. antiemetic utilization is an accepted standard of care with explicit guidelines [@Apfel_15190136; @GanDiemunschHabibEtAl2014].

This paper investigates if antiemetic utilization is predicted by socioeconomic status. We explore the association of the two predictors insurance status and median income in the patients' home zip code with antiemetic utilization of ondansetron and/or dexamethason in the subset of the National Anesthesia Clinical Outcomes Registry (NACOR) with full electronic anesthesia records [@Dutton_21871404].

## Hypothesis

Our hypothesis is that socioeconomic patient characteristics will predict antiemetic utilization after controlling for institutional and geographic variability, patient preoperative risk factors, procedure and anesthesia type and controlling for individual provider behavior.

\newpage

# Methods
We pre-specified our hypothesis and our analysis methods in the fall of 2013, prior to obtaining the data (accessible in an unpublished manuscript in the appendix online), submitted as a graduate course paper. We obtained the Public User File (PUF) of the National Anesthesia Clinical Outcomes Registry (NACOR), from Quarter 4 of 2013, provided and enriched with additional information on antiemetic usage and insurance status by the Anesthesia Quality Institute (AQI) based on the uploaded electronic medical records. AQI had removed all patient identifiers.

The Albert Einstein College of Medicine Institutional Review Board determined that in accordance with the OHRP Guidance on Research Involving Coded Private Information or Biological Specimens, our study does not meet the definition of human subject research as defined by 45 CFR 46.102(f), as the data/specimens were not collected specifically for the proposed research project and are completely de-identified.

NACOR receives information on anesthesia cases from participating institutions and anesthesia providers[@Dutton_21871404]. The data had been uploaded by participating provider institutions. There is a minimum dataset participating provider upload to NACOR, containing mostly demographics. Only a small portion of providers additionally upload the complete electronic anesthesia record including intra-operative physiologic data and administered medications.

Our unit of analysis is the anesthesia case. Without patient identifiers, repeated anesthetics provided to the same individual could not be identified and therefore such cases were analyzed independently. In Quarter 4 of 2013, NACOR contained about one million anesthesia cases with complete electronic anesthesia records. Our AQI created customized dataset contained 441645 cases (superset) where intra-operative antiemetic utilization was electronically accessible; antiemetics were utilized in 234453 cases.

Besides patient demographics and American Association of Anesthesiology risk classification, provider identifier, institution and location, procedure codes and other case characteristics contained in  NACOR's PUF, our customized dataset contained for each anesthesia case additional information indicating, which antimetics if any was administered [dexamethasone, droperidol, ondansetron and/or phenergan]. However, the timing of antiemetic utilization during surgery versus after surgery in the post anesthesia care unit was not specified. The Nacor set contained the median income based on patient’s zip rounded to 1000, generic and detailed insurance information, but with missing data for many cases as detailed in the Supplemental Table 1, where we explored the missingness pattern.

We described the population characteristic of the NACOR datasets forming the bases of our analysis, i.e. anesthesia records with complete information on the administration of antiemetic prophylaxis and/or insurance information, procedure code, median income... We explored the bivariate associations between the dichotomous  outcome variable antiemetic utilization [defined as either the administration of *ondansetron* or of *ondansetron and/or dexamethason*], and the independent variables describing patients, procedures & providers; patient characteristics included medical insurance status (our primary predictor of interest), patient age, gender, American Association of Anesthesiology risk classification. Neither race nor ethnicity was recorded in NACOR. We reported procedure types and indications (Billing code, modifiers, indication ICD code). Provider characteristics include information on the anesthetist [nurse anesthetist versus resident versus attending alone] and institutional data [geographic location, academic versus private versus government institution]. 

## Statistical analysis

We used several different statistical approaches to analyze the data:

1. bivariate analysis,
2. stratified analysis,
3. logistic regression models and
4. mixed effects hierarchical Bayesian models.  

We employed and compared the above in sensitivity and subgroup analyses to investigate if any potential association between socioeconomic status and antiemetic utilization depended on the mode of analysis and/or on the inclusion or exclusion of potential confounders. The regression coefficients reported were all statistically highly significant, but given the size of the dataset, we considered p-values of lesser importance for our inferences than the magnitude and consistency of the observed associations and rarely if ever report them.

### Bivariate and stratified analysis

We used parametric tests where the assumptions of normality did not seem violated and non-parametric test, where graphical or statistical tests suggested possible violations of the underlying assumptions. We reported proportions, mean and standard deviation or the median and the interquartile range (as appropriate for the distribution of values observed for each parameter) and indicated the statistical test used in the table of characteristic of patients. We calculated odds ratios for the association between insurance status and antiemetic administration and with the data stratified by gender, age and other demographics and case characteristics. 

### Classical logistic regression

We fit classical logistic regression models in the superset of anesthesia cases in the National Anesthesia Clinical Outcomes Registry (NACOR) with information on intra-operative antiemetic administration and medical insurance status. We investigated the effect of medical insurance as predictor on the administration of antiemetic medication as primary outcome, controlling for potential confounders like patient characteristics, provider characteristics and procedure type and indication. The predictor insurance status is an ordinal variable; possible values are ordered from highest insurance coverage, i.e. private insurance, Health Maintenance Organization, Medicare, Medicaid, to the lowest no medical insurance reported. Our outcome is dichotomous, antiemetic prophylaxis administered or not. Our unit of analysis is the anesthesia case, not the patient. We focused our analysis on the most frequent procedures performed. We considered findings statistically significant if the p-value was less than the alpha of 0.05.Patients may have several operations, each generating one anesthesia record; patients may hence be counted several times. We will only consider antiemetic prophylaxis administered during anesthesia care, either in the operating room or while dropping off the patient in the recovery unit, but before sign-out to the recovery staff. 

Besides insurance status as our primary outcome, we decided a priori to include gender and age in model, because both have been previously shown to be risk factors for PONV and are hence considered indications for antiemetic prophylaxis; as such they may act as confounders. In addition, we  chose those independent variables for the initial model that show a statistically significant association in the bivariate analysis. We used stepwise backward elimination starting from our initial model based on the likelihood ratio test with a cutoff at 0.05 to eliminate independent variables from the model. For each model eliminated we confirmed that the given variable was not a confounder for the present model. We used a change in the beta coefficient of larger than 20% as our cutoff to determine if a variable is considered a confounder. We determined the correct functional form and explore potential violations of the assumptions of linearity. We ran locally weighted regression of yvar on xvar (and examined the graph for all independent variables in our final model), for a graphical assessment of potential violations of the assumption of linearity. We tested for the correct functional form, fitting fractional polynomials as part of our final logistic regression model. We  examined if the addition of a polynomial improves the model significantly. We explored the potential interaction between the independent variables age and gender in a simple logistic regression model; a cut of for our likelihood ratios test was at an alpha level of 0.05. We examined the goodness of fit with the Hosmer-Lemeshow goodness of fit test. We performed a sensitivity analysis of our model assumptions and choices.

### Bayesian hierarchical model

We build hierarchical Bayesian models for the subset with data on medical insurance (short: *insurance*), median income in patient home zip code (short: *income*), respectively. We studied the administration of *only ondansetron*  or of *ondansetron and dexamethason* as primary outcomes.  We included either *insurance* or *income* [devided in quantiles] as ordinal predictors in our models. We controlled for patient characteristics like gender and age. In some models, we included mixed (random) effects to control for the potential confounding influence of procedure type or provider behavior, by allowing each procedure and each provider to have an individual intercept. We present more formal details on the Bayesian modeling in the appendix. We relied on Rhat as a convergence diagnostic, after exploring the Monte Carlo Markov Chain output graphically[@brooks1998general]. There are no patient identifiers to track repeated anesthetics administered to the same patient. We used the default priors as described in the software package[@rstanarm], i.e. we used uninformative priors for the main effect of insurance status on antiemetic prophylaxis. We performed a sensitivity analysis investigating the appropriateness of our model assumptions. 

We compared the results of our three models (bivariate, logistic regression and Bayesian analysis) to confirm the robustness of our findings regardless of the model choices or statistical approach chosen.

### Software used

We used the statistical software *Stata*\textsuperscript{\textregistered} for the regression and bivariate analysis[@Stata_2014]. We used R, the public domain statistical software package and the probabilistic programming software *Stan* in conjunction with the R software packages *rstan* and *rstanarm* [@R_software; @Stan_Software_2014; @rstanarm] to implement the hierarchical mixed Bayesian models with *Stan’s* Hamiltonian Monte Carlo algorithms. These are available under the General Public License of the Free Software Foundation[@GNU_1991] at no cost. We used the software package *shinyStan* for graphical exploration of model convergence and the Monte Carlo Markov Chain output, to generate the contrasts to compare commercial versus Medicaid and for posterior predictivechecking[@shinystan-software_2015].
\newpage

# Results

## Description of the dataset

Our analysis is focused on the superset of NACOR's PUF with information on  antiemetic usage and its subsets with additional information on insurance status, procedure codes, median income in the patients' home zip code and provider or procedure codes. The flow diagram in Figure 1 details which subset each of our statistical analyses was based on. Our AQI created customized dataset contained 441645 cases (superset) where intra-operative antiemetic utilization was electronically accessible; antiemetics were utilized in 234453 cases. 

Unfortunately, only 441645 cases in the Public User File (PUF) contained detailed information on medications administered during anesthesia administration at the end of 4th quarter 2013. Six unique institutions reported antiemetic utilization **and** insurance status for 173133 anesthesia cases, out of the 12 million cases in NACOR. Limiting this set further to cases with information on additional predictors for a regression analysis (n=115750), or provider and procedure codes shrank the dataset to only 92683 anesthesia cases. We detail this missingness pattern in an additional supplemental table (Supplemental Table 1) in the online supplement. The seven reporting institutions were mostly university hospitals or medium to large community hospitals, mostly in the Southern United States. Our dataset contained no cases from the Midwest or the West of the Unites States. Anesthesia was provided between 2010 and 2013.

### Population characteristics
The demographics of the population in the NACOR database with information on antiemetic administration are described in Table 1. 43 percent of anesthetics were administered to male patients. Patients’ age ranged from newborn to 90 years of age with a median of 52 (Interquartile range (IQR) between 35 and 67 years). Most patients were classified as ASA class 1, 2, 3 or 4 (10, 35, 30, 9
percent, respectively) with few cases in class 5.  62 percent were outpatients among the 64% of cases where this information was available. For 25865 cases the insurances was reported as Medicaid, for another 51441 as Medicare for the remaining 97443 cases as commercial insurance with 1585 self-insured cases, but insurance status was not available in 265311 cases. At least one antiemetic (either ondansetron or dexamethason) was administered in 53 percent of the NACOR superset case. 

### Bivariate comparison of demographic characteristics

We explored the preponderance for antiemetic prophylaxis using ondansetron and/or dexamethason, but present only ondansetron utilization contingent on patient insurance status in Table 2 in a stratified analysis by gender and anesthetic choice, as the results were consistent regardless. Clearly,  Patients who have commercial insurance are more likely to receive antiemetic prophylaxis than those who have Medicaid, in the bivariate analysis and in the stratified analyses.

We stratified the NACOR data set with complete information on insurance status and antiemetic administration into strata by potential confounders as a crude but robust approach to correct for potential confounding. We calculated the odds ratios for receiving ondansetron. Stratification did change the odds ratios contingent on the presence of absence of the predictor, as we would expect for confounders. However in all strata,  Medicaid insurance status was associated with reduced odds of receiving antiemetic prophylaxis suggesting that the strong association between insurance status and antiemetic prophylaxis holds across the board.

We found  statistically significant differences (p<0.001) in all demographic bivariate comparisons; results suggested that patients who received ondansetron were on average younger, as expected considering their higher risk for PONV (postoperative nausea and vomiting). Ondansetron was more frequently given to women, as expected given that women have a higher risk for PONV. Ondansetron was more often used in longer cases, and in outpatients, and less during emergency surgery, and more frequently if the patient lived in a zip code with higher mean income and smaller population size. 

### Logistic regression analysis

We present the results of our final logistic regression model in Table 3, predicting ondansetron use by patient insurance status. Being on Medicaid or Medicare, compared to having commercial insurance, drastically reduces the odds of receiving ondansetron during anesthesia. For the average patient on Medicaid or Medicare, the odds of receiving ondansetron for anti-emetic prophylaxis are 0.6 compared to a patient with commercial insurance with otherwise similar characteristics, even after controlling for age and gender, case duration, median income and population in the patient's home zip code. 

### Hierarchical Bayesian model

We also fitted more complex hierarchical Bayesian mixed effects models to control for procedure and provider influences in the propensity to administer antiemetics. Comparing commercial versus Medicaid or Medicare insurance, or contrasting the differences in median income in the patients home zip code, we consistently found strongly and significantly reduced odds ratio for receiving antiemetic prophylaxis (using ondansetron alone or either ondansetron and/or dexamethason as outcomes) after we fitted several  hierarchical mixed effects Bayesian models (including random intercepts for anesthesia provider, institution, or procedure).  We present the detailed results of several modes in the supplemental online appendix for transparency. The convergence of our Bayesian models was confirmed by looking at traceplots and the Gelman Rubin statistics[@R_hat_Gelman_1992], shown for selected parameters of our Bayesian models.

We show the regression coefficients of one representative Bayesian hierarchical mixed effects model in Table 4. The model predicts ondansetron administration in the NACOR subset of anesthesia cases with complete data on insurance status, antiemetic administration, provider *and* procedure code (n = 92683). Compared to commercial insurance, Medicaid and Medicare patients were less likely to receive antiemetic prophylaxis with ondansetron (OR 0.85, with a 95% Bayesian credible interval of [0.81, 0.89]), after controlling for age, gender, ASA risk classification, anesthesia type, and practice as fixed effects, allowing providers and procedures a random intercept. As we would expect given the known risks for PONV, woman and younger patients were more likely to receive prophylaxis. More prophylaxis was administered in cases using general anesthesia. Increasing ASA risk classification was associated with lower odds of prophylaxis. Differences between institutions were large suggesting that healthcare disparities may be endemic, i.e. locally more or less pronounced. 

## Sensitivity Analysis

The strong and statistically significant association between insurance status and the odds of receiving antiemetic prophylaxis remained unchanged after stratification to control for patient characteristics like gender and age and in our logistic regressions. Our inferences were invariant to the statistical approach (Bayesian versus classical frequentist analysis) we used and bore out in the superset and any subset used for multivariate logistic regression.  

# Discussion

## Summary of the findings

In our enriched National Anesthesia Clinical Outcomes Registry dataset, we found a clinically important and strong statistical association between socioeconomic status (insurance status or median income in home zip code) and the utilization of antiemetic medication (ondansetron and/or dexamethason). Bivariate analysis, stratified analysis, multivariate logistic regression and Bayesian hierarchical modelling all showed the same strong and statistically significant association; for Medicaid versus commercially insured patients, the odds ratio of receiving the antiemetic ondansetron is 0.85 in our Bayesian hierarchical mixed regression model, with a 95% Bayesian credible interval of [0.81, 0.89] with similar inferences in classical regression models and predictors and outcomes. 

The authors believe that socioeconomic status or payer should NOT influence PONV prophylaxis [@Right_to_Health_Lancet2015]. Given that antiemetic administration is the sole domain of the individual anesthesia providers, our results point to possible, unappreciated and worrisome healthcare disparities in anesthesia [@Cook_22353147, @Silber_23719571]. The size of the datsets in NACOR we studied likely makes this the largest study of healthcare disparities in anesthesia undertaken to date. This increased our power to detect an association between insurance status and antiemetic prophylaxis. Controlling for likely confounders decreases the chance that the association is spurious. Demonstrating health care disparities for which only anesthesiologists are accountable, in such a large dataset is novel. The fact that antiemetic administration, (as a marker of anesthesia quality) is exclusively in the domain of the anesthesiologist will likely make a greater impression on the anesthesia community than an intervention, marker or decision in which anesthesiologists are only marginally involved (like procedure time [@Silber_23719571]) or where anesthesiologists are not the sole decision maker [@Tighe2012].

### External and internal validity of our findings 

Our sample is likely not representative of the general patient population undergoing anesthesia in the US, but oversampled academic institutions and the North East; what is more, we only have data from the institutions that uploaded full electronic anesthesia records; these institutions and their anesthesia practices are likely different from the average practice, e.g. academic practice is very different from private practice, with the later presumably catering more to outcomes patients perceive as important, PONV being one of them. Demonstrating differences (or similarities) in the demographic characteristics between the (customized) NACOR dataset and its smaller subsets used in the various analysis we performed, would not add evidence to refute nor to proof that the associations observed are generalizable. Instead our findings pointing to health care disparities in anesthesia are concerning and compelling because they are consistent across *different* data sets. The observed associations seem pervasive, even though we concede (and very much hope) that they may not be ubiquitous. The heterogeneity of US anesthesia practice, (apparent in the variability of the case mix between institutions, and the diversity of its providers, defeats a simplified approach to demonstrate associations across all cases in large databases like NACOR [@SilberKennedyEven-ShoshanEtAl2002 @SchubertEckhoutNgoEtAl2012]. However, the redundancy and multiplicity of our analyses of different subsets together with our final random effects modeling by individual provider and procedure might serve as a model how to address this challenging complexity [@FleisherAnderson2002]? Reporting of antiemetic utilization in our dataset did not differentiate intra-operative when antiemetics would have been administered for prophylaxis, versus postoperative use when antiemetics might have been given as treatment for active vomiting. While consistent under-treatment of patients of lower socioeconomic status would be equally concerning as inferior prophylaxis, treatment in the post anesthesia period is no longer under the sole domain of the anesthesia providers. We concede that this limits our inferences. Not all providers and institution use electronic anesthesia records and if they do they may not upload the data to NACOR, e.g. for regulatory or privacy reasons, all the foregoing may limit the generalizability of our findings. Our analysis should hence be repeated in other larger electronic anesthesia database. Also, providers may have forgotten to record the administration of antiemetic medication, but still have administered the prophylaxis. They may have recorded the dose, but might still have failed to administer the prophylaxis. Both instances of misclassification of outcome (antiemetic prophylaxis administration) could lead to an over- or underestimation of anesthesia healthcare disparities as defined here

Those who do not accept antiemetic utilization as a valid indicator of anesthesia quality, will have to concede that disparities in antiemetic prophylaxis due to insurance or socioeconomic status are worrisome in their own right. On the other hand our main predictors, (insurance status and median income in patients' home zip code), while closely linked to race and socioeconomic status, may not be the best predictors of healthcare disparities; we furthermore concede that our cross-sectional analysis neither discerns causal pathways, nor proves causation.

### Sensitivity analysis   

Each statistical approaches has its limitations. Stratified analysis only controls for the specific variable by which the stratification is done and  substratification quickly becomes overwhelming. Logistic regression does not control well for confounding when the probability of effect is around 0.5. Hierarchical models lead to shrinkage, which makes for a better fit of the model to the data, but this may lead, among other issues, to overfitting. However, our results were invariant to the statistical approach. Regardless of the approach we used (bivariate analysis, stratification, hierarchical Bayesian or classical frequentist logistic regression), we came to the same inferences. We controlled for many patient characteristics like ASA risk classification, age and gender. We controlled for the choice of anesthetic given; we considered surgical procedure and provider as confounding factors by allowing individual random intercepts, implemented in a Bayesian hierarchical model. Likewise, while there was considerable missing data as detailed in the flow diagram in Figure 1, the results were consistent across all subsets analyzed.


## Anesthesiologist are leaders in perioperative quality improvement

In the process of quality improvement, we typically go through the four stages described succinctly by Don Berwick[@Berwick_2909878]:

1. Stage I: “The data are wrong….”
2. Stage II: “The data are right, but it's not a problem…”
3. Stage III: “The data are right, it's a problem, but it's not my problem…”
4. Stage IV: “The data are right, it's a problem, it's my problem…”

We hope to convince anesthesiologists with the presented strong, robust and consistent association between insurance status and antiemetic prophylaxis with ondansetron, that the findings are solid (Stage I). Disparity in anesthesia quality, we hope anesthesiologist will agree, is a problem, even if it concerned not anesthesia quality in general, but only antiemetic prophylaxis (Stage II). We think there is a clear argument that the described association describes healthcare disparity for which anesthesia providers are accountable (Stage III). Anesthesiologist have a tradition as the leaders in perioperative quality improvement addressing individual performance as well as systems to achieve the best of care for all of our patients[@Gaba_10720368].

# Conclusion: 

Our analysis of the association between insurance status (as a marker of patient socioecomonic status) and antiemetic administration (as a marker of anesthesia quality provided by the individual anesthesiologist) in the NACOR database point to possible unappreciated healthcare disparities in anesthesia at the provider level which are worrisome and deserve further investigation and vigorous countermeasures.

# References
