---
output:
  word_document:
    reference_docx: mystyleSupplementalTablesAQI.docx
---

# Table 2 Stratified Analysis

---

```{r, packages, message=FALSE, echo=FALSE, warning=FALSE}
library(knitr) # required to set options in Markdown R
library(dplyr)
library(plyr)
# library(ResourceSelection)
# library(lme4)
# library(nlme)
```



```{r, global_options, echo=FALSE}

# set the directory to the project directory
#setwd("C:/Users/Micheal/Dropbox/Professional/AQI/AQI_Random_Effects_Stan/AQI_Analysis")
# set options
opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE)
rm(list = ls())
showall<-FALSE
```


```{r load_clean_dataset, echo=showall}


## Load cleaned dataset *fullAQI_4_14* and *prov1_AQI_4_14*
load("Data/ManuscriptData15Apr16.Rdata")

# we load the cleaned larger dataset without and with provider information *fullAQI_4_14.Rdata*, *prov1_AQI_4_14*, which we generated in *import_AQI_14Jul2015.Rmd*   

#load("Analysis/Data/fullAQI_4_14.Rdata")
#load("Analysis/Data/prov1_AQI_4_14.Rdata")
```

```{r show_data_structure, eval=showall}
str(fullAQI_4_14)
str(prov1_AQI_4_14)
```


```{r reorder_level_age_group, echo=showall, results='hide'}
## Reorder age_group for tables

levels(fullAQI_4_14$age_group)
fullAQI_4_14$age_group <- factor(fullAQI_4_14$age_group, 
                                 levels =  c("Under 1",
                                             "1-18",
                                             "19 - 49", 
                                             "50 - 64", 
                                             "65 - 79",
                                             "80+"
                                              ))
levels(fullAQI_4_14$age_group)
```

# Table 1

```{r table1_gender}
table1.2 <- ddply(fullAQI_4_14, 
                    c("sex"), summarise,
                    N = length(ond),
                    Percent_n= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )
kable(table1.2, col.names = c("Gender",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron"), 
      digits = 2)
```


```{r table1_age_group}

table1.3 <- ddply(fullAQI_4_14, 
                    c("age_group"), summarise,
                    N = length(ond),
                    Percent_n= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )
kable(table1.3, col.names = c("Age",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron"), 
      digits = 2)
```

```{r table1_anes_type}
table1.4 <- ddply(fullAQI_4_14, 
                    c("anes_type"), summarise,
                    N = length(ond),
                    Percent_n= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )
kable(table1.4, col.names = c("Anesthetic",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron"), 
      digits = 2)
```


```{r table1_ASA}
table1.5 <- ddply(fullAQI_4_14, 
                    c("ASA"), summarise,
                    N = length(ond),
                    Percent_n= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )
kable(table1.5, col.names = c("ASA class",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron"), 
      digits = 2)
```


```{r table1_pay}
table1.6 <- ddply(fullAQI_4_14, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent_n= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )
kable(table1.6, col.names = c("Insurance",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron"), 
      digits = 2)
```

# Table 2


```{r odds_ratio_calculation}
## Function to calculate OR

calculate_OR <- function(mytable) {
  #function to calculate the odds ratios 
  # with the top line the reference odds in a one column table
  Odds_table <- select(mytable, odds_Antiemetic)
  ORtable <- rep(1,dim(Odds_table)[1])
  for (i in 2: (dim(Odds_table)[1]))  {
   ORtable[i] <- Odds_table[i,]/ Odds_table[1,] 
  }
  return(as.data.frame(ORtable))
}

# calculate_OR(table2.1)
# new<- bind_cols(table2, calculate_OR(table2))
```

## Antiemetics by insurance type

```{r odds_ratio1}
table2.1 <- ddply(fullAQI_4_14, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.1 <- bind_cols(table2.1, calculate_OR(table2.1))

kable(tableOR2.1, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2)
```



## Stratificaton 

### Gender

```{r odds_ratio2_female}
Stratification <-filter(fullAQI_4_14, sex=="female")

table2.2 <- ddply(Stratification, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.2 <- bind_cols(table2.2, calculate_OR(table2.2))


kable(tableOR2.2, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2, caption = "Stratified by gender/female")
```


```{r odds_ratio2_male}
Stratification <-filter(fullAQI_4_14, sex=="male")

table2.3 <- ddply(Stratification, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.3 <- bind_cols(table2.3, calculate_OR(table2.3))


kable(tableOR2.3, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2, caption = "Stratified by gender/male")
```

### Anesthesia Type

```{r odds_ratio3_general}
Stratification <-filter(fullAQI_4_14, anes_type=="General")

table2.2 <- ddply(Stratification, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.2 <- bind_cols(table2.2, calculate_OR(table2.2))


kable(tableOR2.2, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2, caption = "Stratified by anes_type/general")
```


```{r odds_ratio2_neuroax}
Stratification <-filter(fullAQI_4_14, anes_type=="Neuroaxial")

table2.3 <- ddply(Stratification, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.3 <- bind_cols(table2.3, calculate_OR(table2.3))


kable(tableOR2.3, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2, caption = "Stratified by anes_type/neuroaxial")
```

```{r odds_ratio3_regional}
Stratification <-filter(fullAQI_4_14, anes_type=="Regional")

table2.2 <- ddply(Stratification, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.2 <- bind_cols(table2.2, calculate_OR(table2.2))


kable(tableOR2.2, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2, caption = "Stratified by anes_type/regional")
```


```{r odds_ratio2_MAC}
Stratification <-filter(fullAQI_4_14, anes_type=="MAC")

table2.3 <- ddply(Stratification, 
                    c("pay"), summarise,
                    N = length(ond),
                    Percent= N/dim(fullAQI_4_14)[1],
                    Ond = sum(ond=="Ondan"),
                    p_Antiemetic = sum(ond=="Ondan")/length(ond),
                    odds_Antiemetic = sum(ond=="Ondan")/sum(ond=="no Ondan")
                    )

tableOR2.3 <- bind_cols(table2.3, calculate_OR(table2.3))


kable(tableOR2.3, col.names = c("Insurance Typ",
                              "Cases",
                              "% Population",
                              "Ondansetron",
                              "% Ondansetron",
                              "Odds for Ondansetron",
                              "Odds Ratio"), 
      digits = 2, caption = "Stratified by anes_type/MAC")
```


